### ISSUE TITLE
1.19.2 IndexOutOfBoundsException

### ISSUE THREAD

**Issue by ouihon** [SistrScarlet/LittleMaidReBirth-Fabric#13]
I played it running in a server with my friend. And as she logged in, I found that I could not log in anymore. It just threw an error "Internel Exception: java.lang.IndexOutOfBoundsException: readerIndex(31) + length(1) exceeds writerIndex(31): PooledUnsafeDirectByteBuf(ridx: 31, widx: 31, cap:31 "

By the way, when I play it by myself, this exception is never thrown. So I guess it is about network synchronization or something... I really love this mod. If you can figure out what the problem is, I'll appreciate it. Thank you!

**Comment by SistrScarlet** [comment]
ご報告ありがとうございます、修正しました。
LMML-5.1.1 / LMRB-5.2.3をお試しください。

**Comment by ouihon** [comment]
すみません、このバージョンのパッケージはどこでダウンロードできるのでしょうか？ リリースにはなかったです！ありがとうございます。
Sorry, where can I download this version of the package? I didn't see it in the release! Thank you very much.

**Comment by SistrScarlet** [comment]
このフォーラム内のDownloadリンクからですね。
https://forum.civa.jp/viewtopic.php?f=3&t=119
もしかして、ここ以外からダウンロードしましたか？
二次配布は特に問題無いですが、私の公開するModはここからしかダウンロードできません。

**Comment by ouihon** [comment]
ご返信ありがとうございました。台湾の掲示板からダウンロードさせていただきました。投稿者は繁体字の翻訳を承認したことを示す画像を添付しています。Google Driveにいくつかのバージョンがあります。もし違法であれば、投稿者に連絡して削除してもらうことも可能です。
https://forum.gamer.com.tw/C.php?bsn=18673&snA=187782&page=1&gothis=971233#971233


Thank you for your reply. I downloaded it from a forum in Taiwan. The poster has attached a picture showing that you have approved the traditional Chinese translation. There are some versions in Google Drive. If it is illegal, I can help you to contact the poster to delete them.

**Comment by SistrScarlet** [comment]
なるほど、了解しました。ライセンス上は特に問題ないため、削除の必要はありませんよ。
配布しているバージョンが古い点は気になりますが、私のフォーラムへのリンクもあるようですし、大丈夫でしょう。
