### ISSUE TITLE
zh_cn.json を更新してください

### ISSUE THREAD

**Issue by erer00gg** [SistrScarlet/LittleMaidReBirth-Fabric#14]
1.19.3/1.19/1.18 の zh_cn.json は、「Default branch 1.18_Architectury」 の zh_cn.json より古いです。 ゲームをプレイしているときに、一部の翻訳が間違っていることに気づきました。 次回LMRBを更新する際は、zh_cn.jsonを更新してください。

**Comment by SistrScarlet** [comment]
ご報告ありがとうございます、修正しました。
