### ISSUE TITLE
[Fabric] Tech Rebornとの競合？

### ISSUE THREAD

**Issue by PTOM76** [SistrScarlet/LittleMaidReBirth-Fabric#16]
Tech Rebornで追加される武器をメイドに持たせるとサーバーを起動できなくなってしまいました。
環境はFabricで、MCバージョンは1.18.2です。
もし、Tech Reborn側の問題であれば申し訳ないです。

Crash Log: https://pastebin.com/UwDDDH0C

updateItems関数からマイクラ内部でDefaultedListを操作しているように思いますが、DefaultedListMixinあたりが少し気になります。

**Comment by SistrScarlet** [comment]
ご報告ありがとうございます、修正しました。
ただし根本的な解決には至っていないので、別の形で同様の不具合が出てくる可能性があります。

**Comment by PTOM76** [comment]
ご修正いただきましてありがとうございます。
