### ISSUE TITLE
ボイスパックをZIP形式で残しておくことはできますか？

### ISSUE THREAD

**Issue by miraclematters** [SistrScarlet/LittleMaidReBirth-Fabric#17]
ボイスパックのインストール方法はこれでいいのでしょうか？LittleMaidMobXのページで入手しました。

![image](https://user-images.githubusercontent.com/65470941/219864769-669c3e68-84ed-410d-9c1d-78f382f6f1a6.png)

**Comment by SistrScarlet** [comment]
そのzipファイルがボイスパックであれば、正しくインストールされているはずです。
ただ、そのZipファイルはおそらくボイスパックではないですね。

ボイスパックに関しては、こちらのページにある"あみたろさん音声uedaカスタム"や、
https://hashibami.nobody.jp/#modtex
こちらのページにあるボイスパックなどを使用することをオススメします。
https://forum.civa.jp/viewtopic.php?f=3&t=57

また、メイドさんのインベントリを開き、音ブロックが描かれたボタンから、そのメイドさんに適用するボイスパックを選択できます。
お望みのボイスパックが適用されていなかった場合にご利用ください。
