### ISSUE TITLE
1.19.3 forge

### ISSUE THREAD

**Issue by homekame** [SistrScarlet/LittleMaidReBirth-Fabric#18]
メイドに農業、料理をさせようとしたのですができません
かまどが近くに置いてあったり、鍬を持たせたりしても何もできません
砂糖は持たせてあります
バージョンは、マイクラ1.19.3です

**Comment by SistrScarlet** [comment]
そもそもLMRBのメイドさんは農業をしません。
料理も以前のバージョンとは仕様が異なっています。
配布フォーラムをよくご確認ください。
