### ISSUE TITLE
1.18バージョンは野生のメイドを見つけることができないようです

### ISSUE THREAD

**Issue by erer00gg** [SistrScarlet/LittleMaidReBirth-Fabric#2]
サバイバルモードで遊んでいたとき、野生のメイドはいないようでした。 クリエイティブモードで10分以上検索しましたが、見つかりませんでした...

**Comment by SistrScarlet** [comment]
メイドさんを自然スポーンさせるのに、Architecturyを利用していましたが、1.18ではその処理が未実装なようです。
Architecturyの対応を待つので、修正には時間がかかります。

とりあえず今は、メイドさんのスポーンエッグをクラフトしてください。
![2021-12-03_00 52 42](https://user-images.githubusercontent.com/63303162/144458967-6859b4b5-07a8-42ba-bf0c-09c0bb65240f.png)
