### ISSUE TITLE
メイドはカスタムバイオームで自然スポーンしない

### ISSUE THREAD

**Issue by cot6** [SistrScarlet/LittleMaidReBirth-Fabric#24]
複数のカスタムバイオームを導入すると、殆どの確率でバニラバイオームに取って代わるため、自然スポーンの既定値がレアとはいえ、遭遇する機会がそもそも無くなってしまいます。

https://github.com/SistrScarlet/LittleMaidReBirth-Architectury/blob/7a089e724e64b90da9ffb313fb40ce11ad8eef2e/common/src/main/java/net/sistr/littlemaidrebirth/setup/ModSetup.java#L49-L55

ローカル環境ではバイオーム タグで判断していますが、これよりも良い基準があるかもしれません。

https://github.com/cot6/LittleMaidReBirth-Architectury/commit/73d6060c29f880ea077ac773cf9eed5decee25ff#diff-ba7d478353bb4f1973761ad310c5c013574c15dab4520d2dd6e0eaa79a9e06d2

**Comment by utsudashinou** [comment]
カスタムバイオームまで対応するのはかなりつらいので、リソースパックを使って追加する方法がいい気がします。

**Comment by cot6** [comment]
@utsudashinou 手法が察せず恐縮なのですが、例えばリソースパックに何を追加すると良いと思いますか？

**Comment by utsudashinou** [comment]
BiomeTagです。Minecraft内では```data/minecraft/tags/worldgen/biome```に存在するデータです。
LMRBのdataにBiomeTagを設定、通常はビルトインのBiomeTagを読んで、カスタムバイオームなど変更したい場合は、リソースパックで上書きしてもらうわけです。
もちろん、実現するにはソースコードの編集が必要です。

**Comment by utsudashinou** [comment]
すみません。リソースパックではなくデータパックでした。

**Comment by SistrScarlet** [comment]
バイオームを追加するModやデータパックのうち、大抵はVILLAGE_~_HAS_STRUCTUREタグにカスタムバイオームが追加されています。
そのためメイドさんが全くスポーンしない、といった事態はあまり起こらないと考えています。
とはいえ可能性としてはあり得ますし、バイオームを指定したい需要もあるでしょうから、対応策を実装しました。

248806c
utsudashinou氏の提案を元に、"スポーンするバイオームを指定するタグ"を設定できるコンフィグを追加しています。
バイオームタグの追加と除外ができますので、これで余程の場合を除き対応できたかと思われます。

ちなみにデフォルトのときVILLAGE_~_HAS_STRUCTUREタグのみで判定を行っている理由は以下3点です。
・村が生成されるほど安全なバイオームなら、メイドさんも安全だろうから
・安全なバイオームであれば、ディメンションに関係なくスポーンしてほしいため
・実装が単純で済むため

**Comment by utsudashinou** [comment]
素晴らしい。実はデータパックでModのデータを上書きできなかったため、違う方法を考えているところでした。
解決できてよかったです。

**Comment by cot6** [comment]
スポーン有無の確認の仕方が正しくないようで実際の問題では無いとのことで、申し訳ございません。
理由については世界観として何となく想像していたので、その方向性を壊そうとは考えていませんでした。
ですから、先回りして実装していただいて申し訳ないのですが、コード管理の負荷になるでしょうから実装は取り下げていただいて結構です。
