### ISSUE TITLE
Configの不使用の項目について

### ISSUE THREAD

**Issue by utsudashinou** [SistrScarlet/LittleMaidReBirth-Fabric#25]
1.20 ブランチ

emergencyTeleportHealthThresholdというConfigの項目があります。が、どこにも参照箇所がありません。何か意図があって存在しているのか、消し忘れなのか、確認したいです。
おそらく、emergencyMaidHealthThresholdと同じ意味合いだと推測しています。

もし意図があるなら、翻訳を追加したほうが良いです。英語と日本語の翻訳が抜けています。

**Comment by SistrScarlet** [comment]
どうやら消し忘れみたいですね、消しておきました。
