### ISSUE TITLE
The maid cannot be harmed

### ISSUE THREAD

**Issue by YEEERZZZ** [SistrScarlet/LittleMaidReBirth-Fabric#28]
Using version：1.20.1，forge47.2.19，LMRB-1.20.1-8.2.2
Testing in Superflat world
config：immortal: false；disableMaidDeath: false（Also tested "ture"）
It seems that the maid will not be harmed in any way,Like magma damage, player attacks，Warden attack。

**Comment by YEEERZZZ** [comment]
Or maybe it's my problem, I don't know,need help plz

**Comment by SistrScarlet** [comment]
おそらく以下のいずれかの項目にゼロが設定されているのだと思われます。
デフォルトでは非戦闘モードのメイドさんがダメージを受けないようになっています。
Perhaps one of the following items is set to zero.
By default, maids in non-combat mode do not take damage.

generalMaidDamageFactor / battleModeMaidDamageFactor / nonBattleModeMaidDamageFactor

**Comment by YEEERZZZ** [comment]
thank you，"NonBattleModeMadDamageFactor" is zero
