### ISSUE TITLE
メイドは経験値オーブを拾うことができるが、プレーヤーがメイドから経験値を取ることができない

### ISSUE THREAD

**Issue by psml-imeji** [SistrScarlet/LittleMaidReBirth-Fabric#29]
経験値オーブはプレーヤーへのように自動的にメイドに飛びますし、メイドも経験値オーブを拾いますが、経験値がプレーヤーへ追加せず、メイドから経験値を取るのもできないので経験値が実際的に破壊されてしまう。

**Comment by SistrScarlet** [comment]
メイドさんが取得した経験値は、空のガラス瓶を持ってメイドさんを右クリックすることで、エンチャントの瓶として回収できます。
